# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5933094aa05e6c4623d9443c8d0ee1fce512ab3521cf1c968fd96543b7a4f43ca58a301c9907ceb8166b46ef8545bea6a04f8bb83e03315d0c909f83987afa

test:
  secret_key_base: cda17112e95d3c0c0e5798dc94f14955ccd1fcc6d3d2ae9cb6b964f36d9940ec9ef55acaa1e74f1923f080155f795ae7b93e5551aca6e988e3c25545285e02e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bda17112e95d3c0c0e5798dcf4f14955ccd1fcc6d3d2ae9cb6b964536d9940ec9ef66acaa1e74f1923f080155f795ae7b93e7771aca6e988e3c25545285e02d9
